### PR TITLE
Resolve Check /core-model-1-4:control-construct testcases should avoi…

### LINKED ISSUE #837: Check /core-model-1-4:control-construct testcases should avoid check of operation key
Problem Description:

Check /core-model-1-4:control-construct testcases should avoid check of operation key .

If we are running security mechanism there is a high chance that operation-key are not constant . So for testcases of Check /core-model-1-4:control-construct in test suite we should avoid operation-key comparison

### PR DESCRIPTION
**Pull request by ManasaBM1**
…d check of operation key

Fixes #837

### CODE REVIEW

**Review by IswaryaaS — CHANGES_REQUESTED** [review]
The solution looks very good . PLease find few comments below:
1. Indent the file as discussed
2. Update the function name in catch block to the expected function name
3. Update the function name , it could be updated to RemoveOperationKeyAttributeFromLtp(). 
4. layer-protocol need not be iterated (just to avoid complexity)

**Comment by ManasaBM1** [comment]
done

**Review by IswaryaaS — CHANGES_REQUESTED** [review]
Few more comments:
1. variables shall be named in lower camel case (operationClientInterfacePac)
2. variables shall be declared with "let" keyword . Here, serverclientinterfacepac is missed for declaring

**Review by IswaryaaS — CHANGES_REQUESTED** [review]
1. /v1/register-yourself :: Attribute configured? :: https attributes updated? :: https-address/ipv-4-address updated? , https-port updated? and domain-name updated? - kindly update the changes in these files
2. /v1/embed-yourself :: Update LTP notified? :: registry-office-port update, old-release-protocol update - kindly update the changes in these files

**Review by IswaryaaS — APPROVED** [review]

**Pull request merged**
