### PR TITLE
issue-262 : uploaded pptx to images

### LINKED ISSUE #262: Add editable src picture for TAC documentation
The TinyApplicationController description contains a picture, which is not editable.
An editable version also needs to be added to the [TAC documentation folder](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/TinyApplicationController)

Next steps:
1. Prathiba to check if she has an editable version of the picture (e.g. ppt), if yes I will upload it
2. if no editable version is available, I will redraw the picture and update the repo accordingly.

### PR DESCRIPTION
**Pull request by DanaSunal**
Fixes #262

### CODE REVIEW

**Review by IswaryaaS — COMMENTED** [review]
The diagram replicated in PPT looks fine. I am just wondering the path in which the PPT has been placed. Could you provide me the path where it has been placed.

**Comment by DanaSunal** [comment]
That's really odd, that it doesn't show it here. 
I uploaded it to doc/TinyApplicationController/images

**Comment by IswaryaaS** [comment]
> That's really odd, that it doesn't show it here. I uploaded it to doc/TinyApplicationController/images

May be lets merge and see for the behavior

**Review by IswaryaaS — APPROVED** [review]

**Comment by IswaryaaS** [comment]
I merged it..but still it is not visible under doc/TinyApplicationController/images, but neither in other folders. Could you try uploading it again in this PR

**Pull request merged**
